#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
BNレコードパーサー: １７．馬主マスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class BNParser:
    """
    BNレコードパーサー

    １７．馬主マスタ
    レコード長: 477 bytes
    VBテーブル名: BANUSI
    """

    RECORD_TYPE = "BN"
    RECORD_LENGTH = 477

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        BNレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"BNレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 馬主コード (位置:12, 長さ:6)
            result["BanusiCode"] = self.decode_field(data[11:17])

            # 5. 馬主名(法人格有) (位置:18, 長さ:64)
            result["BanusiName_Co"] = self.decode_field(data[17:81])

            # 6. 馬主名(法人格無) (位置:82, 長さ:64)
            result["BanusiName"] = self.decode_field(data[81:145])

            # 7. 馬主名半角ｶﾅ (位置:146, 長さ:50)
            result["BanusiNameKana"] = self.decode_field(data[145:195])

            # 8. 馬主名欧字 (位置:196, 長さ:100)
            result["BanusiNameEng"] = self.decode_field(data[195:295])

            # 9. 服色標示 (位置:296, 長さ:60)
            result["Fukusyoku"] = self.decode_field(data[295:355])

            # 10. <本年･累計成績情報> (位置:356, 繰返:2, 長さ:60, 合計:120)
            # 10-1. 本年 設定年 (位置:356, 長さ:4)
            result["H_SetYear"] = self.decode_field(data[355:359])

            # 10-2. 本年 本賞金合計 (位置:360, 長さ:10)
            result["H_HonSyokinTotal"] = self.decode_field(data[359:369])

            # 10-3. 本年 付加賞金合計 (位置:370, 長さ:10)
            result["H_FukaSyokin"] = self.decode_field(data[369:379])

            # 10-4. 本年 着回数 (位置:380, 繰返:6, 長さ:6, 合計:36)
            result["H_ChakuKaisu1"] = self.decode_field(data[379:385])
            result["H_ChakuKaisu2"] = self.decode_field(data[385:391])
            result["H_ChakuKaisu3"] = self.decode_field(data[391:397])
            result["H_ChakuKaisu4"] = self.decode_field(data[397:403])
            result["H_ChakuKaisu5"] = self.decode_field(data[403:409])
            result["H_ChakuKaisu6"] = self.decode_field(data[409:415])

            # 10-5. 累計 設定年 (位置:416, 長さ:4)
            result["R_SetYear"] = self.decode_field(data[415:419])

            # 10-6. 累計 本賞金合計 (位置:420, 長さ:10)
            result["R_HonSyokinTotal"] = self.decode_field(data[419:429])

            # 10-7. 累計 付加賞金合計 (位置:430, 長さ:10)
            result["R_FukaSyokin"] = self.decode_field(data[429:439])

            # 10-8. 累計 着回数 (位置:440, 繰返:6, 長さ:6, 合計:36)
            result["R_ChakuKaisu1"] = self.decode_field(data[439:445])
            result["R_ChakuKaisu2"] = self.decode_field(data[445:451])
            result["R_ChakuKaisu3"] = self.decode_field(data[451:457])
            result["R_ChakuKaisu4"] = self.decode_field(data[457:463])
            result["R_ChakuKaisu5"] = self.decode_field(data[463:469])
            result["R_ChakuKaisu6"] = self.decode_field(data[469:475])

            # 11. レコード区切 (位置:476, 長さ:2)
            result["RecordDelimiter"] = self.decode_field(data[475:477])

            return result

        except Exception as e:
            self.logger.error(f"BNレコードパース中にエラー: {e}")
            return None
