#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
BRレコードパーサー: １６．生産者マスタ

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class BRParser:
    """
    BRレコードパーサー

    １６．生産者マスタ
    レコード長: 545 bytes
    VBテーブル名: SEISAN
    """

    RECORD_TYPE = "BR"
    RECORD_LENGTH = 545

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        BRレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"BRレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 生産者コード (位置:12, 長さ:8)
            result["BreederCode"] = self.decode_field(data[11:19])

            # 5. 生産者名(法人格有) (位置:20, 長さ:72)
            result["BreederName_Co"] = self.decode_field(data[19:91])

            # 6. 生産者名(法人格無) (位置:92, 長さ:72)
            result["BreederName"] = self.decode_field(data[91:163])

            # 7. 生産者名半角ｶﾅ (位置:164, 長さ:72)
            result["BreederNameKana"] = self.decode_field(data[163:235])

            # 8. 生産者名欧字 (位置:236, 長さ:168)
            result["BreederNameEng"] = self.decode_field(data[235:403])

            # 9. 生産者住所自治省名 (位置:404, 長さ:20)
            result["Address"] = self.decode_field(data[403:423])

            # 10. <本年･累計成績情報> (位置:424, 繰返:2, 長さ:60, 合計:120)
            # 10-1. 本年 設定年 (位置:424, 長さ:4)
            result["H_SetYear"] = self.decode_field(data[423:427])

            # 10-2. 本年 本賞金合計 (位置:428, 長さ:10)
            result["H_HonSyokinTotal"] = self.decode_field(data[427:437])

            # 10-3. 本年 付加賞金合計 (位置:438, 長さ:10)
            result["H_FukaSyokin"] = self.decode_field(data[437:447])

            # 10-4. 本年 着回数 (位置:448, 繰返:6, 長さ:6, 合計:36)
            result["H_ChakuKaisu1"] = self.decode_field(data[447:453])
            result["H_ChakuKaisu2"] = self.decode_field(data[453:459])
            result["H_ChakuKaisu3"] = self.decode_field(data[459:465])
            result["H_ChakuKaisu4"] = self.decode_field(data[465:471])
            result["H_ChakuKaisu5"] = self.decode_field(data[471:477])
            result["H_ChakuKaisu6"] = self.decode_field(data[477:483])

            # 10-5. 累計 設定年 (位置:484, 長さ:4)
            result["R_SetYear"] = self.decode_field(data[483:487])

            # 10-6. 累計 本賞金合計 (位置:488, 長さ:10)
            result["R_HonSyokinTotal"] = self.decode_field(data[487:497])

            # 10-7. 累計 付加賞金合計 (位置:498, 長さ:10)
            result["R_FukaSyokin"] = self.decode_field(data[497:507])

            # 10-8. 累計 着回数 (位置:508, 繰返:6, 長さ:6, 合計:36)
            result["R_ChakuKaisu1"] = self.decode_field(data[507:513])
            result["R_ChakuKaisu2"] = self.decode_field(data[513:519])
            result["R_ChakuKaisu3"] = self.decode_field(data[519:525])
            result["R_ChakuKaisu4"] = self.decode_field(data[525:531])
            result["R_ChakuKaisu5"] = self.decode_field(data[531:537])
            result["R_ChakuKaisu6"] = self.decode_field(data[537:543])

            # 11. レコード区切 (位置:544, 長さ:2)
            result["RecordDelimiter"] = self.decode_field(data[543:545])

            return result

        except Exception as e:
            self.logger.error(f"BRレコードパース中にエラー: {e}")
            return None
